version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
      - "6567:6566"

    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=5007
    volumes:
      - .:/app
    networks:
      - backend
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fintech-transfer-db
      POSTGRES_USER: SU
      POSTGRES_PASSWORD: PWD
    ports:
      - "5437:5437"
    networks:
      - backend
networks:
  backend: