server:
  port: 5007

grpc:
  port: 6566

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://postgres:5437/fintech-transfer-db
    username: SU
    password: PWD

management:
  endpoints:
    web:
      exposure:
        include: "*"

base-url: /api